### ISSUE TITLE
Http01 and TlsAlpn simultaneously?

### ISSUE THREAD

**Issue by Crypth** [natemcmaster/LettuceEncrypt#116]
I'm curious about the reasoning to use both http-01 and tls-alpn-01 simultaneously. Is this standard way of doing things or just belt and suspenders?

**Comment by natemcmaster** [comment]
I added tls-alpn-01 because some users were reporting issued with http-01 which I couldn't reproduce. It seemed like something was intercepting the HTTP request before the LettuceEncrypt middleware and redirecting to HTTPS. When I added tls-alpn-01, those users reported that things started working.

I think there is probably a new bug though. I read the RFC for ACME and it seems unclear to me how the CA should handle multiple challenge verifications when only some of them succeed. Does the authorization move to the invalid or valid state? I see some evidence from user logs that having two challenge types might be causing issues. I haven't investigated yet. To repro, I want to intentionally play with Let's Encrypt staging to see how they handle various scenarios.

Ideally, one challenge is issued. Picking which one is tricky with Kestrel. Other than parsing from IServerAddressesFeature, I don't know of a good way to detect if Kestrel is serving HTTPS traffic or not. If it's not, then we need http-01 which is subject to the middleware ordering problem.

**Comment by Crypth** [comment]
Cheers for the response. I very much like prefer the tls-alpn-01 way of doing things and ignore the http-01 altogether, as the certificate is easier to spread (after made exportable) and serve on multinode scenarios. It seemed to me that running http-01 alongside stirred issues but I haven't investigated yet since we're not going to drop it.
