### ISSUE TITLE
Add Support for Google Certificates

### ISSUE THREAD

**Issue by RehanSaeed** [natemcmaster/LettuceEncrypt#263]
Google added support for ACME certificates, it would be nice to add support to this library:

https://scotthelme.co.uk/another-free-ca-to-use-via-acme/

**Comment by Blackclaws** [comment]
If google certificates implement the standard ACME protocol then you could just implement a custom:
ICertificateAuthorityConfiguration and add it to the service collection _after_ adding LettuceEncrypt to overwrite the default:
```
services.TryAddSingleton<ICertificateAuthorityConfiguration, DefaultCertificateAuthorityConfiguration>();
```

**Comment by Mafii** [comment]
@RehanSaeed did you ever try this out? I've spent some time trying to use the current Let's Encrypt staging server, and figured out that the root certificate has to be passed to certes as it is not embedded as resource (the old staging certificate is).

I'm asking because to my knowledge using google's acme server should cause the same problem to appear. So your feedback would be valuable to #279!

**Comment by RehanSaeed** [comment]
Sorry @Mafii, I haven't tried it.

**Comment by natemcmaster** [comment]
I've just merged https://github.com/natemcmaster/LettuceEncrypt/pull/279. Can you take a look at this and see if it solves your problem?

In addition, I am marking this as <kbd>help wanted</kbd>. I would be open to adding some code which will pre-configure the ACME endpoints and issuers to make Google's ACME server work. I don't know what the right settings are myself or how to test it, so I would require help to complete this feature.
