### ISSUE TITLE
Wildcard certificates are not handled properly

### ISSUE THREAD

**Issue by ante-maric** [natemcmaster/LettuceEncrypt#285]
**Describe the bug**
If DomainNames in options contain wildcard, subdomains are not handled and SSL/TLS handshake fails.

**To Reproduce**
1. Using 1.3 version of the library with YARP 2.0
2. Add "some.domain.com" and "*.some.domain.com" to DomainNames of LettuceEncryptOptions
3. After certificate is created correctly try to access any subdomain of some.domain.com
4. SSL/TLS handshake will fail

**Expected behavior**
If I have wildcard domain (*.some.domain.com) CertificateSelector.Select should select correct certificate for all subdomains (web.some.domain.com, home.some.domain.com...)

**Additional context**
The only workaround I have is setting my certificate as FallbackCertificate, which I would argue is not really a proper solution.

**Comment by natemcmaster** [comment]
Did you implement DNS validation? https://github.com/natemcmaster/LettuceEncrypt#when-using-dns-01

**Comment by ante-maric** [comment]
> Did you implement DNS validation? https://github.com/natemcmaster/LettuceEncrypt#when-using-dns-01

Yes, I did. Otherwise certificate would not have been created.

**Comment by SSzretter** [comment]
Is there a working example on how to implement the IDnsChallengeProvider  and replace the NoOpDnsChallengeProvider ?

**Comment by natemcmaster** [comment]
The DNS challenge support was implemented by another contributor, so I didn't test myself, but I found this example on GitHub

https://github.com/IronWatch/IronNAC/blob/543b4ec803467e92921c1608d1c772b48052933e/src/CaptivePortal/Daemons/WebDaemon.cs#L87-L91

**Comment by andywu188** [comment]
![image](https://github.com/natemcmaster/LettuceEncrypt/assets/31318039/48fe3dcf-ba3e-41ce-ba7c-a8f7c152ef36)
![image](https://github.com/natemcmaster/LettuceEncrypt/assets/31318039/c24eda48-c46e-4e86-96d7-2878ec9e7f37)

The reason for this bug is here:
1.
_certs.TryGetValue(domainName, out X509Certificate2 value2)

[TryGetValue] failed to obtain wildcard domain name.

The following is the improvement code:
![image](https://github.com/natemcmaster/LettuceEncrypt/assets/31318039/95250a61-e71c-4293-ba92-d812db5e99e9)

2.
public bool HasCertForDomain(string domainName) => _certs.ContainsKey(domainName);

[ContainsKey] failed to obtain wildcard domain name.

The following is the improvement code:

![image](https://github.com/natemcmaster/LettuceEncrypt/assets/31318039/525b3c90-0725-4ebe-896a-3d285781a2a9)

**Comment by andywu188** [comment]
I developed an Alibaba Cloud DNS verification project for this feature and it has been verified to be successful

https://github.com/andywu188/LettuceEncrypt.Dns.Ali

**Comment by natemcmaster** [comment]
Thanks @andywu188. I've merged your PR and uploaded https://www.nuget.org/packages/LettuceEncrypt/1.3.2-beta.292

Can you help me test and validate this fix works?

**Comment by andywu188** [comment]
> Thanks @andywu188. I've merged your PR and uploaded https://www.nuget.org/packages/LettuceEncrypt/1.3.2-beta.292
> 
> Can you help me test and validate this fix works?

OK, i will  check it out as soon as possible

**Comment by andywu188** [comment]
![image](https://github.com/natemcmaster/LettuceEncrypt/assets/31318039/66a44562-3780-4998-8dfe-615130803ac4)
![image](https://github.com/natemcmaster/LettuceEncrypt/assets/31318039/b1855e77-1d7b-4c24-b20f-383cdedb792c)
![image](https://github.com/natemcmaster/LettuceEncrypt/assets/31318039/2bd1f2ce-420a-4210-9979-facb7b66b877)

very good,  no error.

**Comment by natemcmaster** [comment]
Thank you for the fix and testing!
