### ISSUE TITLE
[Question] IHttpChallengeResponseStore in clustered environment

### ISSUE THREAD

**Issue by SebastianStehle** [natemcmaster/LettuceEncrypt#79]
Hi, works great, but I also had to add this to my dockerfile

```
ENV ASPNETCORE_URLS="https://+;http://+"
```

Otherwise the app was only listening to port 80.

But back to my question: Do I also have to impelement IHttpChallengeResponseStore  when I have multiple http nodes?

If the answer is Yes: Can we make it async (can provide a PR)

**Comment by natemcmaster** [comment]
Never tried this in a cluster. I have basically considered that out of scope, figuring it was easier to just use certbot or SSL termination proxy. I'd be interested to know more about how this goes for you.

I'm just guessing, but I think you'll have to do more than distribute the http challenge  response data. If you don't want to open port 80, you'll need to synchronize the tls-alpn-01 challenge data, too. Also, there is the problem of coordinating the nodes in your cluster. If multiple nodes start up without a cert about the same time, how do you know which one should start the order to Let's Encrypt or which one should renew the cert when it's getting close to expiration?  

It's probably possible to make something work, but requires new extensibility points and writing code to make the nodes in your cluster talk to each other somehow to coordinate the cert request process

**Comment by SebastianStehle** [comment]
Yes, you are right. It is just annoying how much stuff you need in your k8 cluster. I just deployed a nginx ingress controller for that.

**Comment by SebastianStehle** [comment]
My ingress-controller does not work, because I also need http/2 support for the backend, because I am also hosting a grpc service and nginx proxy does not support http/2 to the backend server.

Would it not be enough to support a simple locking mechanism? Should be easy to implement with optimistic concurrency.

**Comment by Crypth** [comment]
I'm thinking about this possibility as well, one solution is to make one server responsible for the challenge and retrieval, and the others redirect to that specific node (with a DNS name) if it gets validation requests. When the certificate is retrieved and stored in a centralized location, tell the other nodes to retrieve and use it. I'm working on another solution, but it may be too specific for my case to share it.

**Comment by webprofusion-chrisc** [comment]
@Crypth off-topic, but I've started building central cert management and an API for pulling latest certs into https://github.com/webprofusion/certify (a .net ACME UI and service) - this would primarily promote using DNS validation but http (and possibly tls-alpn-01) are possible as the middleware could fetch the latest challenge responses to present when they occur (so whichever servers gets hit for http validation they can all participate in serving the challenge responses).

**Comment by natemcmaster** [comment]
>  I'm working on another solution, but it may be too specific for my case to share it.

@Crypth even if your solution isn't reusable, I'm still interested in your use case. 

Before attempting to build cert automation for a clustered environment, I'd like to understand the use cases more. How many nodes are you running? How are you managing nodes? What's the lifecycle of a particular node? How do you handle scaling up and down? Do your nodes have the ability to communicate directly to each other, or share access to a common data store? etc. 

It's too soon for me to say how to build a general solution that works for many.

**Comment by Crypth** [comment]
Clustered environment is a Service Fabric cluster with a standard Azure Load Balancer. The node count of the type that hosts the web server will be subject to change, but 5 at the moment and scaling automatically or maybe programmatically, likely time based. Higher node count during active hours. Node count could at that point be many, but reasonably, 
I'd say less than 10, because the web server part of the nodes are not the essential load running in the cluster. 
The nodes does have intracommunication so i could share the order and response challenge state between them. They share common data store (azure vault for one, but also various databases).

**Comment by natemcmaster** [comment]
Thanks for the details.

Added the help-wanted label. This means I'm open to accepting contributions for this, but don't have immediate plans to build this for you. 

I've also added the 'needs design' label. This issue may be more challenging than others. I'd like to see a written proposal first for the expected behavior first before anyone starts submitting code to implement this. Some of the questions that such a design should address are mentioned in https://github.com/natemcmaster/LettuceEncrypt/issues/79#issuecomment-629598840. In addition, I think we also need to address the question of abstraction - what does the API look like, and is it sufficiently abstract that it can be used in multiple clustered environments?

Let me know if you're interested in contributing.

**Comment by natemcmaster** [comment]
I was reading https://tools.ietf.org/html/rfc8555#section-8.3. Looks like ACME allows for HTTP 302 redirects.

> The server SHOULD follow redirects when dereferencing the URL. Clients might use redirects, for example, so that the response can be provided by a centralized certificate management server. 

This might make it easier to implement. Instead of sharing the HTTP challenge data, have each node redirect to a node dedicated to managing certs. 

Given that, my recommendation for this would be to start by creating one node that used LettuceEncrypt and have all other nodes redirect /.well-known/acme-challenge/* URLS to it. Have that one node share its certificate with the other nodes using one of the ICertificateRepository implementations or your own.

If you find that you need more API from this library to make this happen, please comment about your use case. For example, I can see that it might be challenging to share certificates and manage their rotation on their own. LettuceEncrypt does this already, but it’s internal and tied to the ACME cert generation scenario. I think we could extract the cert management piece into a separate library.

**Comment by Almeonamy** [comment]
How about to store the file with key for challenge in shared storage such as S3 or another? The Let's Encrypt extension for Azure does the same. 
https://github.com/sjkp/letsencrypt-siteextension

**Comment by kamyker** [comment]
@natemcmaster any new ways to do it?

**Comment by kamyker** [comment]
> I was reading https://tools.ietf.org/html/rfc8555#section-8.3. Looks like ACME allows for HTTP 302 redirects.
> 
> > The server SHOULD follow redirects when dereferencing the URL. Clients might use redirects, for example, so that the response can be provided by a centralized certificate management server.
> 
> This might make it easier to implement. Instead of sharing the HTTP challenge data, have each node redirect to a node dedicated to managing certs.
> 
> Given that, my recommendation for this would be to start by creating one node that used LettuceEncrypt and have all other nodes redirect /.well-known/acme-challenge/* URLS to it. Have that one node share its certificate with the other nodes using one of the ICertificateRepository implementations or your own.
> 
> If you find that you need more API from this library to make this happen, please comment about your use case. For example, I can see that it might be challenging to share certificates and manage their rotation on their own. LettuceEncrypt does this already, but it’s internal and tied to the ACME cert generation scenario. I think we could extract the cert management piece into a separate library.

Got it working by doing it. No changes in api needed.

One pod has Lettuce installed and saves cert in kubernetes secret. Other pods can pull from secret or api exposed on that pod.

Instead of doing 302 redirect I'm just proxying /.well-known/acme-challenge/*  calls to that pod. Had to force Http challenge as Tls didn't work.
